### PR TITLE
Login

### LINKED ISSUE #25: Authentication between Google and our backend
We need to establish authentication between Google's oauth and our servers.

### PR DESCRIPTION
**Pull request by charlotte-zhuang**
1. Create endpoint on backend for getting user information and jwt
2. Allow frontend to receive user information and change page to login state
3. see examples for `server/config.env` and `.env`
4. installed `nodemon` on server for convenience

Steps to get working
1. copy `server/config.env.example` to `server/config.env` and `.env.example` to `.env`, then fill in the missing fields. You can leave `JWT_KEY` as is for your dev environment.
2. run `npm i` then `npm start`
3. open new terminal and `cd server`
4. run `npm i` then `npm start`

You should be able to login with google, then the google login button disappears.

Resolves #25 and #6

### CODE REVIEW

**Comment by charlotte-zhuang** [comment]
For authentication between frontend and backend, the frontend will pass the json web token with any requests it makes, then the backend will verify the jwt before taking action.

**Comment by JoshuaLawson8** [comment]
got it working, looks good

**Review by JoshuaLawson8 — APPROVED** [review]
nice

**Review by christinang3030 — APPROVED** [review]
Also works for me and looks good. Super nice!

**Review by isabellapiz — APPROVED** [review]

**Pull request merged**
