### PR TITLE
Fixed user auth

### PR DESCRIPTION
**Pull request by charlotte-zhuang**
1. User's picture url are now being saved in our database
2. Email verified is handled better. It is passed to the frontend instead of automatically rejecting.
3. Added missing user attributes to `src/util/constants.js`

### CODE REVIEW

**Review by isabellapiz — APPROVED** [review]

**Comment by christinang3030** [comment]
How can we access the picture url for example from the profile component? I tried using the getClient function in Profile.jsx and passed it to the clientProfile component but it didn't work :c

**Comment by charlotte-zhuang** [comment]
> How can we access the picture url for example from the profile component? I tried using the getClient function in Profile.jsx and passed it to the clientProfile component but it didn't work :c

@christinang3030 You need to query the User document since the pictureUrl is in that schema.

**Review by JoshuaLawson8 — APPROVED** [review]
👍

**Review by christinang3030 — APPROVED** [review]
how can we access the user's picture? 
do we use the getClient function

**Comment by charlotte-zhuang** [comment]
> how can we access the user's picture?
> do we use the getClient function

Either make a post request to `/user/get` or take the URL from `props.user.pictureUrl`

**Pull request merged**
