### PR TITLE
Style changes

### PR DESCRIPTION
**Pull request by isabellapiz**
Stylized marketplace page, added info to footer, added info to about page, made minor style changes to requests page.

- Home page still needs styling, I didn't know what to do with it

### CODE REVIEW

**Review by charlotte-zhuang — CHANGES_REQUESTED** [review]
The marketplace and PTProfile components don't resize properly on smaller windows. Could you change it back?

**Review by charlotte-zhuang — COMMENTED** [review]
Marketplace and FilterSearch have new display issues when you make the window size more narrow. It looks okay as long as the window is wide. I personally think the CSS from before looks better, but I guess it's ok either way.

**Review by charlotte-zhuang — DISMISSED** [review]
I'm trying to make my previous review not block merging.

**Review by thibui0908 — APPROVED** [review]
had some issues when resizing but otherwise working

**Review by euniceyoh — APPROVED** [review]

**Review by christinang3030 — APPROVED** [review]
look great!

**Pull request merged**
